import 'controller/offline_browsing_controller.dart';import 'package:flutter/material.dart';import 'package:recorrd/core/app_export.dart';import 'package:recorrd/widgets/custom_button.dart';import 'package:recorrd/widgets/custom_radio_button.dart';
// ignore_for_file: must_be_immutable
class OfflineBrowsingBottomsheet extends StatelessWidget {OfflineBrowsingBottomsheet(this.controller);

OfflineBrowsingController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.maxFinite, child: Container(width: double.maxFinite, padding: getPadding(left: 16, top: 21, right: 16, bottom: 21), decoration: AppDecoration.fillWhiteA700.copyWith(borderRadius: BorderRadiusStyle.customBorderTL10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("lbl_offline_reading".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtGilroySemiBold18), Padding(padding: getPadding(top: 27), child: Obx(() => Column(children: [CustomRadioButton(width: getHorizontalSize(394), text: "msg_top_sections_only".tr, value: controller.offlineBrowsingModelObj.value.radioList.value[0], groupValue: controller.radioGroup.value, fontStyle: RadioFontStyle.GilroyMedium18, isRightCheck: true, onChange: (value) {controller.radioGroup.value = value;}), CustomRadioButton(width: getHorizontalSize(394), text: "msg_all_content_updated".tr, iconSize: getHorizontalSize(24), value: controller.offlineBrowsingModelObj.value.radioList.value[1], groupValue: controller.radioGroup.value, margin: getMargin(top: 29), fontStyle: RadioFontStyle.GilroyMedium18, isRightCheck: true, onChange: (value) {controller.radioGroup.value = value;})]))), Padding(padding: getPadding(top: 32, bottom: 14), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomButton(height: getVerticalSize(50), text: "lbl_cancel".tr, margin: getMargin(right: 8), variant: ButtonVariant.OutlineBlueA700_1, fontStyle: ButtonFontStyle.GilroyMedium16BlueA700, onTap: () {onTapCancel();})), Expanded(child: CustomButton(height: getVerticalSize(50), text: "lbl_okay".tr, margin: getMargin(left: 8)))]))])))); } 
onTapCancel() { Get.back(); } 
 }
