// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi7UCgjVpdJfu-ELgYn-r3JgUKaxTtGMk',
    appId: '1:322333828698:web:349e75c18eeef389c55a63',
    messagingSenderId: '322333828698',
    projectId: 'recorrd',
    authDomain: 'recorrd.firebaseapp.com',
    storageBucket: 'recorrd.appspot.com',
    measurementId: 'G-QNJCT5ZGWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdC0uCvS_qmRLBPt8qFvgrjuiYTzQ5C_E',
    appId: '1:322333828698:android:4286bf216aca7af4c55a63',
    messagingSenderId: '322333828698',
    projectId: 'recorrd',
    storageBucket: 'recorrd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_J4X-38lBneT0MORPanDayMVpdg6BPF0',
    appId: '1:322333828698:ios:520a5ae2d4ab7358c55a63',
    messagingSenderId: '322333828698',
    projectId: 'recorrd',
    storageBucket: 'recorrd.appspot.com',
    iosClientId: '322333828698-64aihnlvvosor6qp1s739netalaetklb.apps.googleusercontent.com',
    iosBundleId: 'pro.recorrd.app.recorrd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_J4X-38lBneT0MORPanDayMVpdg6BPF0',
    appId: '1:322333828698:ios:082301b6b3a2a4acc55a63',
    messagingSenderId: '322333828698',
    projectId: 'recorrd',
    storageBucket: 'recorrd.appspot.com',
    iosClientId: '322333828698-f4jb1q42hoeapvfc13smiqs2u5to26i6.apps.googleusercontent.com',
    iosBundleId: 'pro.recorrd.app.recorrd.RunnerTests',
  );
}
